[project]
name = "pidog_rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cvxpy>=1.6.6",
    "cython>=3.1.2",
    "gymnasium>=1.1.1",
    "imageio>=2.37.0",
    "mujoco>=3.3.3",
    "obj2mjcf>=0.0.25",
    "pyqt5>=5.15.11",
    "scipy>=1.15.3",
    "stable-baselines3>=2.6.0",
    "tensorboard>=2.19.0",
]
